{{- if .Values.pinniped.concierge.enabled }}
{{- range $k,$v := .Values.pinniped.concierge.jwtAuths}}
---
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: {{ include "beam.pinniped.concierge.fullname" $ }}-{{ $k }}
  labels:
    {{- include "beam.pinniped.concierge.labels" $ | nindent 4 }}
  namespace: {{ include "beam.namespace" $ }}
spec:
{{ toYaml $v | indent 2 }}
{{- end }}
{{- end }}
