apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contentserver.contentserver.fullname" . }}
  labels:
    {{- include "contentserver.contentserver.labels" . | nindent 4 }}
  namespace: {{ include "contentserver.namespace" . }}
spec:
  {{- if not .Values.contentserver.autoscaling.enabled }}
  replicas: {{ .Values.contentserver.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "contentserver.contentserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "contentserver.contentserver.labels" . | nindent 8 }}
        {{- with .Values.contentserver.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.contentserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "contentserver.serviceAccountName" . }}
      {{- with .Values.contentserver.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contentserver.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contentserver.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: contentserver
          {{- with .Values.contentserver.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          {{- with .Values.contentserver.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.contentserver.service.port }}
              protocol: TCP
          args:
            - -var-dir
            - {{ .Values.persistence.path }}
            {{- if .Values.server.address }}
            - -webserver-address
            - {{ .Values.server.address }}
            - -webserver-path
            - {{ .Values.server.path }}
            {{- end }}
            {{- if .Values.repository.poll }}
            - -poll
            {{- end }}
            - -repository-timeout-duration
            - {{ .Values.repository.timeout }}
            {{- with .Values.contentserver.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - {{ .Values.repository.url }}
          env:
            {{- with .Values.contentserver.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.contentserver.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            {{- toYaml .Values.contentserver.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.contentserver.livenessProbe | nindent 12 }}
          {{- with .Values.contentserver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.contentserver.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "contentserver.contentserver.fullname" . }}
            readOnly: false
        {{- end }}
        {{- with .Values.contentserver.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.contentserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contentserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contentserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.contentserver.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
