{{- if gt (int .Values.contentserver.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "contentserver.contentserver.fullname" . }}
  labels:
    {{- include "contentserver.contentserver.labels" . | nindent 4 }}
  namespace: {{ include "contentserver.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "contentserver.contentserver.selectorLabels" . | nindent 6 }}
  {{- with .Values.contentserver.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
