apiVersion: v1
kind: Service
metadata:
  name: {{ include "contentserver.contentserver.fullname" . }}
  labels:
    {{- include "contentserver.contentserver.labels" . | nindent 4 }}
  {{- with .Values.contentserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "contentserver.namespace" . }}
spec:
  type: {{ .Values.contentserver.service.type }}
  ports:
    - name: http
      port: {{ .Values.contentserver.service.port }}
      targetPort: http
  selector:
    {{- include "contentserver.contentserver.selectorLabels" . | nindent 4 }}
