{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keel.server.fullname" . }}
  labels: {{- include "keel.server.labels" . | nindent 4 }}
  namespace: {{ include "keel.server.namespace" . }}
spec:
  selector:
    matchLabels: {{- include "keel.server.selectorLabels" . | nindent 6 }}
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
