apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gateways.foomo.org
  labels:
    {{- include "gateway.crds.labels" . | nindent 4 }}
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: foomo.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                service:
                  type: string
                  minLength: 1
                  description: k8s service to connect to
                sitemap:
                  type: string
                addToRobots:
                  type: string
                expose:
                  type: array
                  items:
                    type: object
                    properties:
                      stripBasePath:
                        type: boolean
                        description: service is exposed at /foo request is /foo/bar, stripBasePath == true => requests will go to /bar and /foo will be set as x-base-path header
                      description:
                        type: string
                        description: a description of the exposition, to be show in gateway api
                      cmsApp:
                        type: string
                        description: named application in cms
                      paths:
                        type: array
                        minItems: 0
                        description: 'paths in urls to register for, lookup is automatically long to short'
                        items:
                          type: string
                      cmsMimetypes:
                        type: array
                        minItems: 0
                        description: contentserver mimetypes
                        items:
                          type: string
                      internalAccessGroups:
                        type: array
                        minItems: 0
                        description: access is only granted to these internal groups
                        items:
                          type: string
              required:
                - service

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gateways
    # singular name to be used as an alias on the CLI and for display
    singular: gateway
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Gateway
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - gw
