{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "contentserver.fullname" . }}
  labels: {{- include "contentserver.labels" . | nindent 4 }}
  namespace: {{ include "contentserver.namespace" . }}
spec:
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  podSelector:
    matchLabels: {{- include "contentserver.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    {{- if .Values.networkPolicy.ingress.allowExternal }}
    - from:
        - podSelector:
            matchLabels:
              networking/allow-{{- include "contentserver.fullname" . }}-access: "true"
    {{- end }}
    {{ with .Values.networkPolicy.ingress.additionalRules }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{ if .Values.networkPolicy.egress.allowExternal }}
    - to:
        - podSelector:
            matchLabels:
              networking/allow-{{- include "contentserver.fullname" . }}-access: "true"
    {{- end }}
    {{ with .Values.networkPolicy.egress.additionalRules }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}

