{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "contentserver.fullname" . }}
  labels:
    {{- include "contentserver.labels" . | nindent 4 }}
  namespace: {{ include "contentserver.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "contentserver.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "contentserver.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
