{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contentserver.serviceAccountName" . }}
  labels:
    {{- include "contentserver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "contentserver.namespace" . }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
