apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sesamy.gtm.preview.fullname" . }}
  labels:
    {{- include "sesamy.gtm.preview.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm.namespace" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.preview.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      {{- include "sesamy.gtm.preview.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sesamy.gtm.preview.labels" . | nindent 8 }}
        {{- with .Values.preview.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/proxy/configmap.yaml") . | sha256sum }}
        {{- with .Values.preview.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "sesamy.gtm.serviceAccountName" . }}
      {{- with .Values.preview.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.preview.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.preview.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gtm-preview-proxy
          {{- with .Values.proxy.image }}
          image: {{ .repository }}:{{ .tag }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - name: https
              containerPort: 443
          readinessProbe:
            tcpSocket:
              port: 443
          livenessProbe:
            tcpSocket:
              port: 443
          {{- with .Values.proxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: gtm-preview-proxy-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: gtm-preview-proxy-certs
              mountPath: /etc/nginx/ssl
              readOnly: true
        - name: gtm-preview
          {{- with .Values.gtm.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          {{- with .Values.preview.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.preview.service.port }}
              protocol: TCP
          env:
            - name: CONTAINER_CONFIG
              value: {{ .Values.gtm.containerConfig | quote }}
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.gtm.googleCloudProject | quote }}
            - name: RUN_AS_PREVIEW_SERVER
              value: "true"
            {{- with .Values.preview.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.preview.extraEnvFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.preview.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.preview.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.preview.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.preview.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.preview.extraVolumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.scheduling.enabled }}
      {{- with .Values.scheduling.priorityClass }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.scheduling.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{ $labelSelector := dict
          "labelSelector" (dict
            "matchLabels" (include "sesamy.gtm.preview.selectorLabels" $)
          )
        }}
        {{- range . }}
        - {{ toYaml (mergeOverwrite $labelSelector .) | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- end }}
      volumes:
        - name: gtm-preview-proxy-config
          configMap:
            name: {{ include "sesamy.gtm.proxy.fullname" . }}
        - name: gtm-preview-proxy-certs
          secret:
            secretName: {{ include "sesamy.gtm.proxy.fullname" . }}
        {{- with .Values.preview.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.preview.dnsConfig }}
      dnsConfig: {{- toYaml . | nindent 8 }}
      {{- end }}
