{{- if .Values.umami.enabled }}
{{- if not .Values.umami.config.appSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sesamy.umami.umami.fullname" . }}-app
  labels:
    {{- include "sesamy.umami.umami.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.umami.namespace" . }}
type: Opaque
data:
  {{- if .Values.umami.config.appSecret.secret }}
  {{ default "app-secret" .Values.umami.config.appSecret.existingSecretKey }}: {{ .Values.umami.config.appSecret.secret | b64enc }}
  {{- else }}
  {{ default "app-secret" .Values.umami.config.appSecret.existingSecretKey }}: {{ randAlphaNum 50 | b64enc }}
  {{- end }}
---
{{- end }}
{{- if not .Values.umami.config.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sesamy.umami.umami.fullname" . }}-db
  labels:
    {{- include "sesamy.umami.umami.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.umami.namespace" . }}
type: Opaque
data:
  {{ default "database-uri" .Values.umami.config.database.existingSecretKey }}: {{ include "sesamy.umami.umami.database.uri" . | b64enc }}
---
{{- end }}
{{- end }}
