{{- if .Values.pinniped.supervisor.enabled }}
{{- range $k,$v := .Values.githubProviders}}
---
apiVersion: v1
kind: Secret
type: "secrets.pinniped.dev/github-client"
metadata:
  name: {{ include "beam.pinniped.supervisor.fullname" $ }}-github-{{ $k }}
  labels:
    {{- include "beam.pinniped.supervisor.labels" $ | nindent 4 }}
  namespace: {{ include "beam.namespace" $ }}
stringData:
  clientID: {{ $v.clientId }}
  clientSecret: {{ $v.clientSecret }}
{{- end }}
{{- end }}
