# yaml-language-server: $schema=values.schema.json

# @schema
# type: object
# additionalProperties: true
# @schema
global:
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  foomo:
    # @schema
    # type: boolean
    # @schema
    # Enable for backward compatibility
    # @section -- Global
    withDeprecatedSelectorLabels: false
    # @schema
    # type: object
    # @schema
    squadron:
      # @schema
      # type: string
      # @schema
      # -- Squadron name
      # -- Will be automatically injected
      # @section -- Global
      name: ''
      # @schema
      # type: string
      # @schema
      # -- Squadron unit name
      # -- Will be automatically injected
      # @section -- Global
      unit: ''
      # @schema
      # type: string
      # @schema
      # -- Squadron fleet name
      # -- Will be automatically injected (optional)
      # @section -- Global
      fleet: ''

# @schema
# type: string
# @schema
# -- Overrides the chart's name
# @section -- Overrides
nameOverride: ''
# @schema
# type: string
# @schema
# -- Overrides the chart's computed fullname
# @section -- Overrides
fullnameOverride: ''
# @schema
# type: string
# @schema
# -- The name of the Namespace to deploy
# @section -- Overrides
namespaceOverride: ''

# @schema
# type: integer
# @schema
# -- Number of revisions to keep
# @section -- General
revisionHistoryLimit: 10
# @schema
# type: object
# additionalProperties: true
# @schema
# -- Map of environment variables to add
# @section -- General
env: { }
# env:
#   FOO: bar
# @schema
# type: object
# additionalProperties: true
# @schema
# -- Map of environment variables to add as a secret
# @section -- General
secretEnv: { }
# secretEnv:
#   FOO: bar
# @schema
# type: array
# items:
#   type: string
# @schema
# -- List of existing secrets to be mounted
# @section -- General
secretMounts: []
# secretMounts:
#   - my-secret
# @schema
# enum: [RollingUpdate, Recreate]
# @schema
# -- Deployment update strategy
# @section -- General
updateStrategy: RollingUpdate
# @schema
# type: number
# @schema
# -- Number of replications
# @section -- General
replicas: 1

# @schema
# type: object
# @schema
# Log settings
log:
  # @schema
  # enum: [prod, dev]
  # @schema
  # -- Log mode
  # @section -- Log settings
  mode: prod
  # @schema
  # enum: [error, warn, info, debug]
  # @schema
  # -- Log level
  # @section -- Log settings
  level: info

# @schema
# type: object
# @schema
# OpenTelemetry settings
otel:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether to enable it or not
  # @section -- OpenTelemetry settings
  enabled: false
  # @schema
  # type: integer
  # @schema
  # -- Trace ratio
  # @section -- OpenTelemetry settings
  ratio: 1
  # @schema
  # type: object
  # @schema
  # -- OTLP exporter settings
  # @section -- OpenTelemetry settings
  otlp:
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to use insecure connection
    # @section -- OpenTelemetry settings
    insecure: true
    # @schema
    # type: string
    # @schema
    # -- Enpoint uri
    # @section -- OpenTelemetry settings
    endpoint: 'alloy:4317'
  # @schema
  # type: object
  # @schema
  # GORM settings
  gorm:
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to enable it or not
    # @section -- OpenTelemetry settings
    enabled: true
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to trace sql attributes
    # @section -- OpenTelemetry settings
    sqlParametersDisabled: true
  # @schema
  # type: object
  # @schema
  # Mongo settings
  # @section -- OpenTelemetry settings
  mongo:
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to enable it or not
    # @section -- OpenTelemetry settings
    enabled: true
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to trace command attributes
    # @section -- OpenTelemetry settings
    commandAttributeDisabled: true
  # @schema
  # type: object
  # @schema
  # GOTSRPC settings
  # @section -- OpenTelemetry settings
  gotsrpc:
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to enable it or not
    # @section -- OpenTelemetry settings
    enabled: true
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to trace payload attributes
    # @section -- OpenTelemetry settings
    payloadAttributeDisabled: true

# @schema
# type: object
# @schema
# Image settings
image:
  # @schema
  # type: boolean
  # @schema
  # -- Force recreation
  # @section -- Image settings
  recreate: false
  # @schema
  # enum: [IfNotPresent, Always]
  # @schema
  # -- Image tag
  # @section -- Image settings
  pullPolicy: IfNotPresent
  # @schema
  # type: array
  # items:
  #   type: string
  # @schema
  # -- Image pull secrets
  # @section -- Image settings
  pullSecrets: [ ]
  # @schema
  # type: string
  # required: true
  # @schema
  # -- Image repository
  # @section -- Image settings
  repository: ''
  # @schema
  # type: string
  # required: true
  # @schema
  # -- Image tag
  # @section -- Image settings
  tag: ''

# @schema
# type: object
# @schema
# Ingress settings
ingress:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether the ingress is enabled or not
  # @section -- Ingress settings
  enabled: false
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional labels
  # @section -- Ingress settings
  additionalLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Ingress annotations
  # @section -- Ingress settings
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  # @schema
  # type: string
  # @schema
  # -- Ingress class name
  # @section -- Ingress settings
  className: ''
  # @schema
  # type: array
  # items:
  #   type: string
  # @schema
  # -- List of hosts
  # @section -- Ingress settings
  hosts: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   properties:
  #     path:
  #       type: string
  #     port:
  #       type: integer
  #     pathType:
  #       enum: [ImplementationSpecific, Exact, Prefix]
  # @schema
  # -- List of hosts
  # @section -- Ingress settings
  paths: [ ]
  # paths:
  #   - path: /foo
  #     port: 8080
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- TLS settings
  # @section -- Ingress settings
  tls: [ ]
  # tls:
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local

# @schema
# type: object
# @schema
# Persistence settings
persistence:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether a pv should be attached or not
  # @section -- Persistence settings
  enabled: false
  # @schema
  # type: string
  # @schema
  # -- Storage mount path
  # @section -- Persistence settings
  mountPath: /var/lib/cronjob/data
  # @schema
  # enum: [ReadWriteOnce, ReadOnlyMany, ReadWriteMany]
  # @schema
  # -- Access mode
  # @section -- Persistence settings
  accessMode: ReadWriteOnce
  # @schema
  # type: string
  # @schema
  # -- Storage size
  # @section -- Persistence settings
  size: 1Gi
  # @schema
  # type: string
  # @schema
  # -- Storage class name
  # @section -- Persistence settings
  storageClass: ''

# @schema
# type: object
# @schema
# Service settings
service:
  # @schema
  # type: string
  # @schema
  # -- Service type
  # @section -- Service settings
  type: ClusterIP
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional Service labels
  # @section -- Service settings
  additionalLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Service annotations
  # @section -- Service settings
  annotations: { }

# @schema
# type: object
# @schema
# Security context
securityContext:
  # @schema
  # type: integer
  # @schema
  # -- Run as user id
  # @section -- Security context
  runAsUser: 10001
  # @schema
  # type: integer
  # @schema
  # -- Run as group id
  # @section -- Security context
  runAsGroup: 10001
  # @schema
  # type: integer
  # @schema
  # -- File system group id
  # @section -- Security context
  fsGroup: 10001
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether to run as non root user
  # @section -- Security context
  runAsNonRoot: true

# @schema
# type: object
# @schema
# Server settings
server:
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional labels
  # @section -- Server settings
  additionalLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Deployment annotations
  # @section -- Server settings
  annotations: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Pod annotations
  # @section -- Server settings
  podAnnotations: { }
  # @schema
  # type: array
  # items:
  #   type: object
  #   properties:
  #     name:
  #       type: string
  #     value:
  #       type: string
  #   additionalProperties: true
  # @schema
  # -- Additional environment variables
  # @section -- Server settings
  additionalEnv: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Additional env from
  # @section -- Server settings
  additionalEnvFrom: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   properties:
  #     name:
  #       type: string
  #     mountPath:
  #       type: string
  #   additionalProperties: true
  # @schema
  # -- Additional volume mounts
  # @section -- Server settings
  additionalVolumeMounts: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Additional volumes
  # @section -- Server settings
  additionalVolumes: [ ]
  # additionalVolumes:
  #   - name: my-existing-volume-name
  #     storageClass: local-path
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Host aliases
  # @section -- Server settings
  hostAliases: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Additional ports
  # @section -- Server settings
  additionalPorts: [ ]
  # @schema
  # type: [object, null]
  # additionalProperties: true
  # @schema
  # -- Resource settings
  # @section -- Server settings
  resources: {}
  # @schema
  # type: [object, null]
  # additionalProperties: true
  # @schema
  # -- Startup probe settings
  # @section -- Server settings
  startupProbe:
    tcpSocket:
      port: 3000
  # @schema
  # type: [object, null]
  # additionalProperties: true
  # @schema
  # -- Readiness probe settings
  # @section -- Server settings
  readinessProbe:
    tcpSocket:
      port: 3000
  # @schema
  # type: [object, null]
  # additionalProperties: true
  # @schema
  # -- Liveness probe settings
  # @section -- Server settings
  livenessProbe:
    tcpSocket:
      port: 3000

# @schema
# type: object
# @schema
# Autoscaling settings
autoscaling:
  # @schema
  # type: boolean
  # @schema
  # -- Specifies whether a auto scaling should be enabled
  # @section -- Autoscaling settings
  enabled: false
  # @schema
  # type: integer
  # @schema
  # -- Minimum replication number
  # @section -- Autoscaling settings
  minReplicas: 1
  # @schema
  # type: integer
  # @schema
  # -- Maximum replication number
  # @section -- Autoscaling settings
  maxReplicas: 9
  # @schema
  # type: [integer, string]
  # @schema
  # -- Minimum availablity
  # @section -- Autoscaling settings
  minAvailable: ''
  # @schema
  # type: [integer, string]
  # @schema
  # -- Maximum unavailablity
  # @section -- Autoscaling settings
  maxUnavailable: 1
  # @schema
  # type: [integer, null]
  # @schema
  # -- Target CPU utilization
  # @section -- Autoscaling settings
  targetCPU: 75
  # @schema
  # type: [integer, null]
  # @schema
  # -- Target Memory utilization
  # @section -- Autoscaling settings
  targetMemory: null
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional scaling metrics
  # @section -- Autoscaling settings
  additionalMetrics: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Autoscaling behavior settings
  # @section -- Autoscaling settings
  behavior: { }

# @schema
# type: object
# @schema
# Service account settings
serviceAccount:
  # @schema
  # type: string
  # @schema
  # -- The name of the service account to use.
  # @section -- Service account settings
  name: ""
  # @schema
  # type: boolean
  # @schema
  # -- Specifies whether a service account should be created
  # @section -- Service account settings
  create: true
  # @schema
  # type: boolean
  # @schema
  # -- Automatically mount a ServiceAccount's API credentials?
  # @section -- Service account settings
  automount: true
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Annotations to add to the service account
  # @section -- Service account settings
  annotations: { }

# @schema
# type: object
# @schema
# Service Monitor settings
serviceMonitor:
  # @schema
  # type: boolean
  # @schema
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  # @section -- Service Monitor settings
  enabled: false
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional ServiceMonitor labels
  # @section -- Service Monitor settings
  additionalLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- ServiceMonitor annotations
  # @section -- Service Monitor settings
  annotations: { }
  # @schema
  # type: string
  # @schema
  # -- ServiceMonitor scrape interval
  # @section -- Service Monitor settings
  interval: ''
  # @schema
  # type: string
  # @schema
  # -- ServiceMonitor scrape timeout in Go duration format (e.g. 15s)
  # @section -- Service Monitor settings
  scrapeTimeout: ''
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- ServiceMonitor will add labels from the service to the Prometheus metric
  # @section -- Service Monitor settings
  targetLabels: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- ServiceMonitor relabel configs to apply to samples before scraping.
  # @section -- Service Monitor settings
  relabelings: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- ServiceMonitor metric relabel configs to apply to samples before ingestion
  # @section -- Service Monitor settings
  metricRelabelings: [ ]

# @schema
# type: object
# @schema
# Network Policy settings
networkPolicy:
  # @schema
  # type: boolean
  # @schema
  # -- Specifies whether Network Policies should be created
  # @section -- Network Policy settings
  enabled: false
  # @schema
  # type: array
  # items:
  #   type: string
  # @schema
  # -- List of rules to apply via labels
  # @section -- Network Policy settings
  rules: []
  # rules:
  #   - allow-nginx-ingress
  #   - allow-internet-egress
  #   - allow-my-service-access
  # @schema
  # type: object
  # @schema
  # Ingress settings
  # @section -- Network Policy settings
  ingress:
    # @schema
    # type: boolean
    # @schema
    # -- Specifies whether ingress should be enabled
    # @section -- Network Policy settings
    enabled: true
    # @schema
    # type: boolean
    # @schema
    # -- Allow ingress through labels
    # @section -- Network Policy settings
    allowExternal: true
    # @schema
    # type: array
    # items:
    #   type: string
    #   additionalProperties: true
    # @schema
    # -- Additional ingress rules
    # @section -- Network Policy settings
    additionalRules: []
  # @schema
  # type: object
  # @schema
  # Egress settings
  # @section -- Network Policy settings
  egress:
    # @schema
    # type: boolean
    # @schema
    # -- Specifies whether egress should be enabled
    # @section -- Network Policy settings
    enabled: true
    # @schema
    # type: boolean
    # @schema
    # -- Allow ingress through labels
    # @section -- Network Policy settings
    allowExternal: true
    # @schema
    # type: array
    # items:
    #   type: string
    # @schema
    # -- Additional egress rules
    # @section -- Network Policy settings
    additionalRules: []

# @schema
# type: object
# @schema
# Graceful settings
graceful:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether graceful shutdown is enabled
  # @section -- Graceful settings
  enabled: false
  # @schema
  # type: integer
  # @schema
  # -- Seconds to wait for kubernetes to deregister
  # @section -- Graceful settings
  delaySeconds: 15
  # @schema
  # type: integer
  # @schema
  # -- Total seconds for the grace period
  # @section -- Graceful settings
  periodSeconds: 45

# @schema
# type: object
# @schema
# Scheduling settings
scheduling:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether scheduling is enabled or not
  # @section -- Scheduling settings
  enabled: false
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Affinity for pod assignment
  # @section -- Scheduling settings
  affinity: {}
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Node labels for pod assignment
  # @section -- Scheduling settings
  nodeSelector: {}
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Tolerations for pod assignment
  # @section -- Scheduling settings
  tolerations: []
  # @schema
  # type: [string, null]
  # additionalProperties: true
  # @schema
  # -- Priority class name
  # @section -- Scheduling settings
  priorityClass: null

# @schema
# type: object
# @schema
# Foomo gateway settings
gateway:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether the gateway is enabled or not
  # @section -- Gateway settings
  enabled: false
  # @schema
  # type: string
  # @schema
  # -- Sitemap
  # @section -- Gateway settings
  sitemap: ''
  # @schema
  # type: string
  # @schema
  # -- Robots.txt
  # @section -- Gateway settings
  addToRobots: ''
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionProperties: true
  # @schema
  # -- Expose settings
  # @section -- Gateway settings
  expose: []
  # expose:
  #   - stripBasePath: true
  #     cmsMimetypes:
  #       - application/x-page
  #       - application/x-folder
  #       - application/x-shortcut

# @schema
# type: object
# @schema
# RBAC settings
rbac:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether scheduling is enabled or not
  # @section -- RBAC settings
  enabled: false
