apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-dump-env
  labels: {{- include "backups.labels" . | nindent 4 }}
  namespace: {{ include "backups.namespace" . }}
type: Opaque
stringData: 
{{ include "backups.dump.secrets" . | trim | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-upload-env
  labels: {{- include "backups.labels" . | nindent 4 }}
  namespace: {{ include "backups.namespace" . }}
type: Opaque
stringData: 
{{ include "backups.upload.secrets" . | trim | nindent 2 }}