{{- if .Values.pinniped.concierge.enabled }}
{{- range $k,$v := .Values.teams}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pinniped-{{ $k }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $v.role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $v.team }}
{{- end }}
{{- end }}
