{{- if .Values.prizma.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prizma-configmap
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
    }
    stream {
        map_hash_max_size 256;
        map_hash_bucket_size 256;
        map $ssl_preread_server_name $name {
        {{- range $k,$v := .Values.prizma.refractions}}
        {{ $v.from }} {{ $k }};
        {{- end }}
        default https_default_backend;
        }

        {{- range $k,$v := .Values.prizma.refractions}}
        upstream {{$k}} {
            server {{ $v.to }};
        }
        {{- end }}

        upstream https_default_backend {
            server 127.0.0.1:443;
        }

        server {
            listen 443;
            proxy_pass $name;
            ssl_preread on;
        }
    }
{{- end }}

