apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sesamy.gtm.proxy.fullname" . }}
  labels:
    {{- include "sesamy.gtm.proxy.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm.namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "proxy.tls.crt not set" .Values.proxy.tls.crt }}
  tls.key: {{ required "proxy.tls.key not set." .Values.proxy.tls.key }}
