{{- if .Values.collect.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sesamy.gtm.collect.fullname" . }}
  labels: {{- include "sesamy.gtm.collect.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm.namespace" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.collect.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      {{- include "sesamy.gtm.collect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sesamy.gtm.collect.labels" . | nindent 8 }}
        {{- with .Values.collect.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.collect.image.recreate }}
        helm.sh/chart: {{ include "sesamy.gtm.chart-revision" . }}
        {{- end }}
        {{- with .Values.collect.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "sesamy.gtm.serviceAccountName" . }}
      {{- with .Values.collect.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.collect.hostAliases }}
      hostAliases: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.collect.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gtm-collect
          {{- with .Values.collect.image }}
          image: "{{ .repository }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          {{- with .Values.collect.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range $name, $port := $.Values.collect.service.ports }}
            - name: {{ $name }}
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
            {{- with .Values.collect.extraPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.collect.extraEnv }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collect.extraEnvFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collect.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collect.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collect.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collect.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collect.extraVolumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.scheduling.enabled }}
      {{- with .Values.scheduling.priorityClass }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.scheduling.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{ $labelSelector := dict
          "labelSelector" (dict
            "matchLabels" (include "sesamy.gtm.collect.selectorLabels" $)
          )
        }}
        {{- range . }}
        - {{ toYaml (mergeOverwrite $labelSelector .) | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.collect.extraVolumes }}
      volumes: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.collect.dnsConfig }}
      dnsConfig: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
