apiVersion: v1
kind: Service
metadata:
  name: {{ include "sesamy.gtm.collect.fullname" . }}
  labels:
    {{- include "sesamy.gtm.collect.labels" . | nindent 4 }}
  {{- with .Values.collect.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "sesamy.gtm.namespace" . }}
spec:
  type: {{ .Values.collect.service.type }}
  ports:
    - name: http
      port: {{ .Values.collect.service.port }}
      targetPort: http
  selector:
    {{- include "sesamy.gtm.collect.selectorLabels" . | nindent 4 }}
