{{- range $key, $value := .Values.clusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $key }}
  labels: 
    {{- include "namespace.labels" $ | nindent 4 }}
    {{- with $value.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $value.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
rules: {{- toYaml .rules | nindent 2 }}
---
{{- end }}
