{{- range $key, $value := .Values.clusterRoleBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $key }}
  labels:
    {{- include "namespace.labels" $ | nindent 4 }}
    {{- with $value.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with $value.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "namespace.namespace" $ }}
subjects: {{- tpl (toYaml $value.subjects) $ | nindent 2 }}
roleRef:
  kind: {{ $value.kind }}
  name: {{ $value.role }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
