{{- range $key, $value := .Values.externalSecrets }}
{{- if and (lookup "v1" "Namespace" "" "") (not ($.Capabilities.APIVersions.Has "external-secrets.io/v1/ExternalSecret")) }}
{{- fail (printf "ExternalSecret '%s' requires the external-secrets.io/v1 CRD. Install the External Secrets Operator first." $key) }}
{{- end }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $key }}
  labels:
    {{- include "namespace.labels" $ | nindent 4 }}
    {{- with $value.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $value.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "namespace.namespace" $ }}
spec:
  {{- with $value.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $value.refreshPolicy }}
  refreshPolicy: {{ . }}
  {{- end }}
  secretStoreRef: {{- toYaml $value.secretStoreRef | nindent 4 }}
  target:
    name: {{ default $key ($value.target).name }}
    {{- with $value.target }}
    {{- with .creationPolicy }}
    creationPolicy: {{ . }}
    {{- end }}
    {{- with .deletionPolicy }}
    deletionPolicy: {{ . }}
    {{- end }}
    {{- with .template }}
    template: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- with $value.data }}
  data: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $value.dataFrom }}
  dataFrom: {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
