{{- range $key, $value := .Values.tlsSecrets }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $key }}{{ if not $.Values.disableSuffix }}-tls{{ end }}
  labels: {{- include "namespace.labels" $ | nindent 4 }}
  {{- with $value.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "namespace.namespace" $ }}
data: {{- toYaml $value.data | nindent 2 }}
---
{{- end }}
