{{- range $key, $value := .Values.dockerSecrets }}
apiVersion: v1
kind: Secret
type: "kubernetes.io/dockerconfigjson"
metadata:
  name: {{ $key }}-docker
  labels: {{- include "namespace.labels" $ | nindent 4 }}
  {{- with $value.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "namespace.namespace" $ }}
data:
  .dockerconfigjson: {{ $value.data }}
---
{{- end }}
