{{- range $key, $value := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $key }}
  labels: {{- include "namespace.labels" $ | nindent 4 }}
  {{- with $value.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "namespace.namespace" $ }}
---
{{- end }}
