# yaml-language-server: $schema=values.schema.json

# @schema
# type: string
# @schema
# -- Overrides the chart's name
# @section -- Overrides
nameOverride: ''
# @schema
# type: string
# @schema
# -- Overrides the chart's computed fullname
# @section -- Overrides
fullnameOverride: ''
# @schema
# type: string
# @schema
# -- The name of the Namespace to deploy
# @section -- Overrides
namespaceOverride: ''
# @schema
# type: boolean
# @schema
# -- Disable suffixes
# @section -- General
disableSuffix: false
# @schema
# type: object
# additionalProperties: true
# @schema
# -- Cluster Roles to create
# @section -- General
clusterRoles: {}
# clusterRoles:
#   my-cluster-role:
#     annotations: {}
#     labels: {}
#     rules: {}
# @schema
# type: object
# additionalProperties:
#   type: object
#   properties:
#     annotations:
#       type: object
#       additionalProperties: true
#     subjects:
#       type: array
#       additionalProperties: true
#     kind:
#       type: string
#       additionalProperties: true
#     role:
#       type: string
#       additionalProperties: true
# @schema
# -- Role Bindings to create
# @section -- General
roleBindings: {}
# roleBindings:
#   my-role-binding:
#     annotations:
#       replicator.v1.mittwald.de/replicate-to: ".*"
#     group: ""
#     role: ""
# @schema
# type: object
# additionalProperties:
#   type: object
#   properties:
#     annotations:
#       type: object
#       additionalProperties: true
#     data:
#       type: object
#       additionalProperties: true
#     stringData:
#       type: object
#       additionalProperties: true
# @schema
# -- Opaque secrets
# @section -- General
secrets: {}
# secrets:
#   my-secret:
#     annotations:
#       replicator.v1.mittwald.de/replicate-to: ".*"
#     data: {}
# @schema
# type: object
# additionalProperties:
#   type: object
#   properties:
#     annotations:
#       type: object
#       additionalProperties: true
#     data:
#       type: object
#       additionalProperties: true
# @schema
# -- TLS secrets
# @section -- General
tlsSecrets: {}
# tlsSecrets:
#   my-domain.com:
#     annotations:
#       replicator.v1.mittwald.de/replicate-to: ".*"
#     data:
#       tls.crt: ''
#       tls.key: ''
# @schema
# type: object
# additionalProperties:
#   type: object
#   properties:
#     annotations:
#       type: object
#       additionalProperties: true
#     data:
#       type: string
# @schema
# -- Docker config json secrets
# @section -- General
dockerSecrets: {}
# dockerSecrets:
#   hub.docker.com:
#     annotations:
#       replicator.v1.mittwald.de/replicate-to: ".*"
#     data: '{...}'

# @schema
# type: object
# additionalProperties:
#   type: object
#   properties:
#     annotations:
#       type: object
#       additionalProperties: true
# @schema
# -- Service accounts settings
# @section -- General
serviceAccounts: {}
#  my-service-account:
#    annotations: {}

# @schema
# type: object
# additionalProperties:
#   type: object
#   properties:
#     annotations:
#       type: object
#       additionalProperties: true
#   additionalProperties: true
# @schema
# -- Service accounts settings
# @section -- General
volumeClaims: {}
# volumeClaims:
#   my-volume:
#     name: my-existing-volume
#     annotations: {}
#     storageClass: local-path
#     size: 1Gi


