{{- if .Values.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sesamy.gtm.tagging.fullname" . }}
  labels:
    {{- include "sesamy.gtm.tagging.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sesamy.gtm.tagging.selectorLabels" . | nindent 6 }}
  {{- with .Values.autoscaling.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
