{{- if .Values.gtm.googleApplicationCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sesamy.gtm.tagging.fullname" . }}
  labels:
    {{- include "sesamy.gtm.tagging.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm.namespace" . }}
type: Opaque
data:
  google_application_credentials: {{ .Values.gtm.googleApplicationCredentials | quote }}
{{- end }}
