apiVersion: v1
kind: Service
metadata:
  name: {{ include "sesamy.gtm.tagging.fullname" . }}
  labels: {{- include "sesamy.gtm.tagging.labels" . | nindent 4 }}
  {{- with .Values.tagging.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "sesamy.gtm.namespace" . }}
spec:
  type: {{ .Values.tagging.service.type }}
  {{- with .Values.tagging.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.tagging.service.port }}
      targetPort: http
      {{- if and (eq "NodePort" .Values.tagging.service.type) .Values.tagging.service.nodePort }}
      nodePort: {{ .Values.tagging.service.nodePort }}
      {{- end }}
      protocol: TCP
      {{- with .Values.tagging.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  selector: {{- include "sesamy.gtm.tagging.selectorLabels" . | nindent 4 }}
