{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "squadron.server.fullname" . }}
  labels: {{- include "squadron.server.labels" . | nindent 4 }}
  namespace: {{ include "squadron.server.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "squadron.server.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemory }}
    {{- end }}
    {{- with .Values.autoscaling.additionalMetrics }}
      {{- toYaml . | nindent 6 }}
    {{- end}}
  {{- with .Values.autoscaling.behavior }}
  behavior: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
