{{- if .Values.routing.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "squadron.server.fullname" . }}
  labels: {{- include "squadron.server.labels" . | nindent 4 }}
  namespace: {{ include "squadron.server.namespace" . }}
spec:
  {{- with .Values.routing.parentRefs }}
  parentRefs: {{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.routing.paths }}
    - matches:
        - path:
            type: {{ default .pathType "PathPrefix" }}
            value: {{ .path }}
      backendRefs:
        - name: {{ include "squadron.server.fullname" $ }}
          port: {{ .port }}
    {{- end }}
{{- end }}
