{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squadron.server.fullname" . }}-env
  labels: {{- include "squadron.server.labels" . | nindent 4 }}
  namespace: {{ include "squadron.server.namespace" . }}
type: Opaque
stringData: {{ toYaml .Values.secretEnv | nindent 2 }}
---
{{- end }}
{{- range $key, $value := .Values.secrets }}
{{- if $value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squadron.server.fullname" $ }}-{{ $key }}
  labels: {{- include "squadron.server.labels" $ | nindent 4 }}
  namespace: {{ include "squadron.server.namespace" $ }}
type: Opaque
{{- with $value.data }}
data: {{ toYaml $value | nindent 2 }}
{{- end }}
{{- with $value.stringData }}
stringData: {{ toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
