{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "squadron.server.serviceAccountName" . }}
  labels: {{- include "squadron.server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "squadron.server.namespace" . }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
