apiVersion: v2
type: application
name: contentserver
description: Helm chart for the foomo Content Server.
icon: https://avatars.githubusercontent.com/u/889755?s=200&v=4
home: https://www.foomo.org
keywords:
  - foomo
  - foomo-contentserver
sources:
  - https://github.com/foomo/helm-charts
  - https://github.com/foomo/contentserver
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/foomo/helm-charts
    - name: Image Source
      url: https://github.com/foomo/contentserver

version: 0.0.3-rc.2
appVersion: 1.11.0-rc.10
