# @schema
# type: string
# @schema
# -- Overrides the chart's name
# @section -- Overrides
nameOverride: ''
# @schema
# type: string
# @schema
# -- Overrides the chart's computed fullname
# @section -- Overrides
fullnameOverride: ''
# @schema
# type: string
# @schema
# -- The name of the Namespace to deploy
# @section -- Overrides
namespaceOverride: ''

# @schema
# type: integer
# @schema
# -- Number of revisions to keep
# @section -- General
revisionHistoryLimit: 10
# @schema
# enum: [RollingUpdate, Recreate]
# @schema
# -- Deployment update strategy
# @section -- General
updateStrategy: RollingUpdate
# @schema
# type: number
# @schema
# -- Number of replications
# @section -- General
replicas: 1

# @schema
# type: object
# @schema
# Log settings
log:
  # @schema
  # enum: [prod, dev]
  # @schema
  # -- Log mode
  # @section -- Logging
  mode: prod
  # @schema
  # enum: [error, warn, info, debug]
  # @schema
  # -- Log level
  # @section -- Logging
  level: info

# @schema
# type: object
# @schema
# OpenTelemetry settings
otel:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether to enable it or not
  # @section -- OpenTelemetry
  enabled: false
  # @schema
  # type: integer
  # @schema
  # -- Trace ratio
  # @section -- OpenTelemetry
  ratio: 1
  # @schema
  # type: object
  # @schema
  # -- OTLP exporter settings
  # @section -- OpenTelemetry
  otlp:
    # @schema
    # type: boolean
    # @schema
    # -- Indicates wether to use insecure connection
    # @section -- OpenTelemetry
    insecure: true
    # @schema
    # type: string
    # @schema
    # -- Enpoint uri
    # @section -- OpenTelemetry
    endpoint: 'alloy:4317'

# @schema
# type: object
# @schema
# Persistence storage settings
persistence:
  # @schema
  # type: boolean
  # @schema
  # -- Enable persistent storage
  # @section -- Persistence
  enabled: false
  # @schema
  # type: string
  # @schema
  # -- Storage class to be used
  # @section -- Persistence
  storageClass: ''
  # @schema
  # type: string
  # @schema
  # -- File storage location
  # @section -- Persistence
  path: '/var/lib/contentserver'
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Labels for the PVC
  # @section -- Persistence
  labels: {}
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Annotations for the PVC
  # @section -- Persistence
  annotations: {}
  # @schema
  # type: array
  # items:
  #   type: string
  # @schema
  # -- Access modes for the PVC
  # @section -- Persistence
  accessModes:
    - ReadWriteOnce
  # @schema
  # type: string
  # @schema
  # -- Storage size
  # @section -- Persistence
  size: 1Gi

# Content Server
contentserver:
  # @schema
  # type: string
  # @schema
  # -- Path to export the webserver on
  # @section -- Content Server
  basePath: '/contentserver'
  # @schema
  # type: object
  # @schema
  # Repository settings
  repository:
    # @schema
    # type: string
    # @schema
    # -- Repository server url
    # @section -- Content Server
    url: http://contentserverexport:8080
    # @schema
    # type: boolean
    # @schema
    # -- If true, the address arg will be used to periodically poll the content url e.g. http://contentserverexport:8080/poll-revision
    # @section -- Content Server
    poll: false
    # @schema
    # type: string
    # @schema
    # -- Update poll interval
    # @section -- Content Server
    pollInterval: 60s
  # @schema
  # type: object
  # @schema
  # Your custom collect image
  image:
    # @schema
    # enum: [IfNotPresent, Always]
    # @schema
    # -- Image tag
    # @section -- Content Server
    pullPolicy: IfNotPresent
    # @schema
    # type: string
    # required: true
    # @schema
    # -- Image repository
    # @section -- Content Server
    repository: foomo/contentserver
    # @schema
    # type: string
    # @schema
    # -- Image tag
    # @section -- Content Server
    tag: 1.12.0
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional Content Server labels
  # @section -- Content Server
  extraLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Content Server annotations
  # @section -- Content Server
  annotations: { }
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Host aliases
  # @section -- Content Server
  hostAliases: []
  # -- Image pull secrets
  # @section -- Content Server
  imagePullSecrets: []
  # -- Annotations for pods
  # @section -- Content Server
  podAnnotations: {}
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Labels for pods
  # @section -- Content Server
  podLabels: {}
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Resource request & limits
  # @section -- Content Server
  resources: {}
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Startup probe settings for pods
  # @section -- Content Server
  startupProbe:
    httpGet:
      path: /healthz/startup
      port: 9400
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Readiness probe settings for pods
  # @section -- Content Server
  readinessProbe:
    httpGet:
      path: /healthz/readiness
      port: 9400
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Liveness probe settings for pods
  # @section -- Content Server
  livenessProbe:
    httpGet:
      path: /healthz/liveness
      port: 9400
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Environment variables to add
  # @section -- Content Server
  extraEnv: []
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Arguements to add
  # @section -- Content Server
  extraArgs: []
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Port definitions to add
  # @section -- Content Server
  extraPorts: []
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Environment variables from secrets or configmaps to add
  # @section -- Content Server
  extraEnvFrom: []
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Volume mounts to add
  # @section -- Content Server
  extraVolumeMounts: []
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Volumes to add
  # @section -- Content Server
  extraVolumes: []
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # Container Security context
  securityContext:
    # @schema
    # type: boolean
    # @schema
    # -- Controls whether a process can gain more privileges than its parent process
    # @section -- Content Server
    allowPrivilegeEscalation: false
    # @schema
    # type: boolean
    # @schema
    # -- Mounts the container's root filesystem as read-only
    # @section -- Content Server
    readOnlyRootFilesystem: true
    # @schema
    # type: object
    # additionalProperties: true
    # @schema
    # -- Grant certain privileges to a process without granting all the privileges of the root user
    # @section -- Content Server
    capabilities: { drop: [ ALL ] }

# @schema
# type: object
# @schema
# Service settings
service:
  # @schema
  # type: string
  # @schema
  # -- Service type
  # @section -- Service
  type: ClusterIP
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional Service labels
  # @section -- Service
  additionalLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Service annotations
  # @section -- Service
  annotations: { }

# @schema
# type: object
# additionalProperties: true
# @schema
# Pod Security context
securityContext:
  # @schema
  # type: integer
  # @schema
  # -- Run as user id
  # @section -- Security Context
  runAsUser: 1001
  # @schema
  # type: integer
  # @schema
  # -- Run as group id
  # @section -- Security Context
  runAsGroup: 1001
  # @schema
  # type: integer
  # @schema
  # -- File system group id
  # @section -- Security Context
  fsGroup: 1001
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether to run as non root user
  # @section -- Security Context
  runAsNonRoot: true
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Restrict a Container's Syscalls with seccomp
  # @section -- Security Context
  seccompProfile: { type: RuntimeDefault }

# @schema
# type: object
# @schema
# Ingress settings
ingress:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether the ingress is enabled or not
  # @section -- Ingress
  enabled: false
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional labels
  # @section -- Ingress
  additionalLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Ingress annotations
  # @section -- Ingress
  annotations: { }
  # @schema
  # type: string
  # @schema
  # -- Ingress class name
  # @section -- Ingress
  className: ''
  # @schema
  # type: array
  # items:
  #   type: string
  # @schema
  # -- List of hosts
  # @section -- Ingress
  hosts: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   properties:
  #     path:
  #       type: string
  #     port:
  #       type: integer
  #     pathType:
  #       enum: [ImplementationSpecific, Exact, Prefix]
  # @schema
  # -- List of hosts
  # @section -- Ingress
  paths: [ ]
  # paths:
  #   - path: /foo
  #     port: 8080
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- TLS settings
  # @section -- Ingress
  tls: [ ]
  # tls:
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local

# @schema
# type: object
# @schema
# Routing settings
routing:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether routing is enabled or not
  # @section -- Routing
  enabled: false
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Path matches
  # @section -- Routing
  paths: []
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Parent references
  # @section -- Routing
  parentRefs: []

# @schema
# type: object
# @schema
# Service account settings
serviceAccount:
  # @schema
  # type: string
  # @schema
  # -- The name of the service account to use.
  # @section -- Service Account
  name: ""
  # @schema
  # type: boolean
  # @schema
  # -- Specifies whether a service account should be created
  # @section -- Service Account
  create: false
  # @schema
  # type: boolean
  # @schema
  # -- Automatically mount a ServiceAccount's API credentials?
  # @section -- Service Account
  automount: false
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Annotations to add to the service account
  # @section -- Service Account
  annotations: { }

# @schema
# type: object
# @schema
# Service Monitor settings
serviceMonitor:
  # @schema
  # type: boolean
  # @schema
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  # @section -- Service Monitor
  enabled: false
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional ServiceMonitor labels
  # @section -- Service Monitor
  additionalLabels: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- ServiceMonitor annotations
  # @section -- Service Monitor
  annotations: { }
  # @schema
  # type: string
  # @schema
  # -- ServiceMonitor scrape interval
  # @section -- Service Monitor
  interval: ''
  # @schema
  # type: string
  # @schema
  # -- ServiceMonitor scrape timeout in Go duration format (e.g. 15s)
  # @section -- Service Monitor
  scrapeTimeout: ''
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- ServiceMonitor will add labels from the service to the Prometheus metric
  # @section -- Service Monitor
  targetLabels: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- ServiceMonitor relabel configs to apply to samples before scraping.
  # @section -- Service Monitor
  relabelings: [ ]
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- ServiceMonitor metric relabel configs to apply to samples before ingestion
  # @section -- Service Monitor
  metricRelabelings: [ ]

# @schema
# type: object
# @schema
# Autoscaling settings
autoscaling:
  # @schema
  # type: boolean
  # @schema
  # -- Specifies whether a auto scaling should be enabled
  # @section -- Autoscaling
  enabled: false
  # @schema
  # type: integer
  # @schema
  # -- Minimum replication number
  # @section -- Autoscaling
  minReplicas: 1
  # @schema
  # type: integer
  # @schema
  # -- Maximum replication number
  # @section -- Autoscaling
  maxReplicas: 9
  # @schema
  # type: [integer, string]
  # @schema
  # -- Minimum availablity
  # @section -- Autoscaling
  minAvailable: ''
  # @schema
  # type: [integer, string]
  # @schema
  # -- Maximum unavailablity
  # @section -- Autoscaling
  maxUnavailable: 1
  # @schema
  # type: [integer, null]
  # @schema
  # -- Target CPU utilization
  # @section -- Autoscaling
  targetCPU: 75
  # @schema
  # type: [integer, null]
  # @schema
  # -- Target Memory utilization
  # @section -- Autoscaling
  targetMemory: null
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Additional scaling metrics
  # @section -- Autoscaling
  additionalMetrics: { }
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Autoscaling behavior settings
  # @section -- Autoscaling
  behavior: { }

# @schema
# type: object
# @schema
# Network Policy
networkPolicy:
  # @schema
  # type: boolean
  # @schema
  # -- Specifies whether Network Policies should be created
  # @section -- Network Policy
  enabled: false
  # @schema
  # type: array
  # items:
  #   type: string
  # @schema
  # -- List of rules to apply via labels
  # @section -- Network Policy
  rules: []
  # rules:
  #   - allow-nginx-ingress
  #   - allow-internet-egress
  #   - allow-my-service-access
  # @schema
  # type: object
  # @schema
  # Ingress settings
  # @section -- Network Policy
  ingress:
    # @schema
    # type: boolean
    # @schema
    # -- Specifies whether ingress should be enabled
    # @section -- Network Policy
    enabled: true
    # @schema
    # type: boolean
    # @schema
    # -- Allow ingress through labels
    # @section -- Network Policy
    allowExternal: true
    # @schema
    # type: array
    # items:
    #   type: string
    #   additionalProperties: true
    # @schema
    # -- Additional ingress rules
    # @section -- Network Policy
    additionalRules: []
  # @schema
  # type: object
  # @schema
  # Egress settings
  # @section -- Network Policy
  egress:
    # @schema
    # type: boolean
    # @schema
    # -- Specifies whether egress should be enabled
    # @section -- Network Policy
    enabled: true
    # @schema
    # type: boolean
    # @schema
    # -- Allow ingress through labels
    # @section -- Network Policy
    allowExternal: true
    # @schema
    # type: array
    # items:
    #   type: string
    # @schema
    # -- Additional egress rules
    # @section -- Network Policy
    additionalRules: []

# @schema
# type: object
# @schema
# Graceful settings
graceful:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether graceful shutdown is enabled
  # @section -- Graceful Shutdown
  enabled: false
  # @schema
  # type: integer
  # @schema
  # -- Seconds to wait for kubernetes to deregister
  # @section -- Graceful Shutdown
  delaySeconds: 15
  # @schema
  # type: integer
  # @schema
  # -- Total seconds for the grace period
  # @section -- Graceful Shutdown
  periodSeconds: 45

# @schema
# type: object
# @schema
# Scheduling settings
scheduling:
  # @schema
  # type: boolean
  # @schema
  # -- Indicates wether scheduling is enabled or not
  # @section -- Scheduling
  enabled: false
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Affinity for pod assignment
  # @section -- Scheduling
  affinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: In
              values: [""]
  # @schema
  # type: object
  # additionalProperties: true
  # @schema
  # -- Node labels for pod assignment
  # @section -- Scheduling
  nodeSelector: {}
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Tolerations for pod assignment
  # @section -- Scheduling
  tolerations: []
  # @schema
  # type: [string, null]
  # @schema
  # -- Priority class name
  # @section -- Scheduling
  priorityClass: null
  # @schema
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- Tolerations for pod assignment
  # @section -- Scheduling
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: DoNotSchedule
      matchLabelKeys:
        - pod-template-hash
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: ScheduleAnyway

# @schema
# type: object
# @schema
# RBAC settings
rbac:
  # @schema
  # type: boolean
  # @schema
  # -- Create PodSecurityPolicy
  # @section -- RBAC
  enabled: false
