# -- Overrides the chart's name
nameOverride: ""
# -- Overrides the chart's computed fullname
fullnameOverride: ""
# -- The name of the Namespace to deploy
# If not set, `.Release.Namespace` is used
namespaceOverride: ''

# -- Number of revisions to retain to allow rollback
revisionHistoryLimit: 10

# Server configuration
server:
  # --- Address to bind web server host:port, when empty no webserver will be spawned
  address: ':8080'
  # -- Path to export the webserver on - useful when behind a proxy e.g. /contentserver
  path: '/contentserver'
# Repository configuration
repository:
  # --- If true, the address arg will be used to periodically poll the content url e.g. http://contentserverexport:8080/poll-revision
  poll: false
  # -- Repository server url e.g. http://contentserverexport:8080
  url: ''
  # --- Timeout duration for the contentserver
  timeout: '2m'


# Persistence storage settings
persistence:
  # -- Enable persistent storage
  enabled: false
  # --- Storage class to be used
  storageClass: ''
  # --- File storage location
  path: '/var/lib/contentserver'
  # -- Labels for the PVC
  labels: {}
  # -- Annotations for the PVC
  annotations: {}
  # -- Access modes for the PVC
  accessModes:
    - ReadWriteOnce
  # -- Storage size
  size: 1Gi

# Content Server
contentserver:
  # Your custom collect image
  image:
    # -- The image repository
    repository: 'foomo/contentserver'
    # -- The image pull policy
    pullPolicy: IfNotPresent
    # -- The image tag
    tag: '1.10.2'
  # -- Always roll your deployment
  roll: false
  # -- Number of replicas
  replicaCount: 1
  # -- Pod Disruption Budget maxUnavailable
  maxUnavailable: null
  # -- Host aliases to add
  hostAliases: []
  #  - ip: 1.2.3.4
  #    hostnames:
  #      - domain.tld
  # -- Image pull secrets
  imagePullSecrets: []
  # -- Annotations for pods
  podAnnotations: {}
  # -- Labels for pods
  podLabels: {}
  # -- The SecurityContext for pods
  podSecurityContext: {}
  #  fsGroup: 2000
  securityContext: {}
  #  capabilities:
  #    drop:
  #      - ALL
  #  readOnlyRootFilesystem: true
  #  runAsNonRoot: true
  #  runAsUser: 1000
  service:
    # -- Port of the service
    port: 8080
    # -- Type of the service
    type: ClusterIP
    # -- Annotations for the service
    annotations: {}
    # -- Labels for service
    labels: {}
  # -- Resource request & limits.
  resources: {}
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  # -- Startup probe settings for pods.
  startupProbe:
    tcpSocket:
      port: 8080
  # -- Readiness probe settings for pods.
  readinessProbe:
    tcpSocket:
      port: 8080
  # -- Liveness probe settings for pods.
  livenessProbe:
    tcpSocket:
      port: 8080
  autoscaling:
    # -- Enable autoscaling
    enabled: false
    # -- Minimum autoscaling replicas
    minReplicas: 1
    # -- Maximum autoscaling replicas
    maxReplicas: 100
    # -- Target CPU utilisation percentage
    targetCPUUtilizationPercentage: 80
    # -- Target memory utilisation percentage
    targetMemoryUtilizationPercentage: null
    # -- Custom metrics using the HPA/v2 schema (for example, Pods, Object or External metrics)
    customMetrics: []
    #  - type: Pods
    #    pods:
    #      metric:
    #        name: loki_lines_total
    #      target:
    #        type: AverageValue
    #        averageValue: 10k
    behavior:
      # -- Enable autoscaling behaviours
      enabled: false
      # -- Scale down policies, must conform to HPAScalingRules
      scaleDown: {}
      # -- Scale up policies, must conform to HPAScalingRules
      scaleUp: {}
  # -- Environment variables to add
  extraEnv: []
  # -- Arguements to add
  extraArgs: []
  # -- Port definitions to add
  extraPorts: []
  # -- Environment variables from secrets or configmaps to add
  extraEnvFrom: []
  # -- Volume mounts to add
  extraVolumeMounts: []
  #  - name: foo
  #    mountPath: "/etc/foo"
  #    readOnly: true
  # -- Volumes to add
  extraVolumes: []
  #  - name: foo
  #    secret:
  #      secretName: mysecret
  #      optional: false
  # -- Tolerations settings for pods.
  nodeSelector: {}
  # -- Tolerations settings for pods.
  tolerations: []
  # -- Affinity settings for pods.
  affinity: {}
  # -- DNSConfig settings for pods.
  dnsConfig: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  paths:
    - path: /contentserver
      pathType: Prefix
      port: 8080
  hosts:
    - example.com
  tls: []
  #  - secretName: example-com-tls
  #    hosts:
  #      - example.com

# ServiceAccount configuration
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

# ServiceMonitor configuration
serviceMonitor:
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: false
  # -- Alternative namespace for ServiceMonitor resources
  namespace: null
  # -- Namespace selector for ServiceMonitor resources
  namespaceSelector: {}
  # -- Optional expressions to match on
  matchExpressions: []
  #  - key: prometheus.io/service-monitor
  #    operator: NotIn
  #    values:
  #      - "false"
  # -- ServiceMonitor annotations
  annotations: {}
  # -- Additional ServiceMonitor labels
  labels: {}
  # -- ServiceMonitor scrape interval
  interval: null
  # -- ServiceMonitor scrape timeout in Go duration format (e.g. 15s)
  scrapeTimeout: null
  # -- ServiceMonitor relabel configs to apply to samples before scraping
  # https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#relabelconfig
  relabelings: []
  # -- ServiceMonitor metric relabel configs to apply to samples before ingestion
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint
  metricRelabelings: []
  ##ServiceMonitor will add labels from the service to the Prometheus metric
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitorspec
  targetLabels: []
  # -- ServiceMonitor will use http by default, but you can pick https as well
  scheme: http
  # -- ServiceMonitor will use these tlsConfig settings to make the health check requests
  tlsConfig: null

# NetworkPolicy configuration
networkPolicy:
  # -- Specifies whether Network Policies should be created
  enabled: false
  metrics:
    # -- Specifies the Pods which are allowed to access the metrics port.
    # As this is cross-namespace communication, you also need the namespaceSelector.
    podSelector: {}
    # -- Specifies the namespaces which are allowed to access the metrics port
    namespaceSelector: {}
    # -- Specifies specific network CIDRs which are allowed to access the metrics port.
    # In case you use namespaceSelector, you also have to specify your kubelet networks here.
    # The metrics ports are also used for probes.
    cidrs: []
  ingress:
    # -- Specifies the Pods which are allowed to access the http port.
    # As this is cross-namespace communication, you also need the namespaceSelector.
    podSelector: {}
    # -- Specifies the namespaces which are allowed to access the http port
    namespaceSelector: {}
  externalStorage:
    # -- Specify the port used for external storage, e.g. AWS S3
    ports: []
    # -- Specifies specific network CIDRs you want to limit access to
    cidrs: []
  discovery:
    # -- Specify the port used for discovery
    port: null
    # -- Specifies the Pods labels used for discovery.
    # As this is cross-namespace communication, you also need the namespaceSelector.
    podSelector: {}
    # -- Specifies the namespace the discovery Pods are running in
    namespaceSelector: {}

# RBAC configuration
rbac:
  # -- Create PodSecurityPolicy.
  enabled: false
