# yaml-language-server: $schema=../values.schema.json
# Use case: Standalone supervisor

pinniped:
  enabled: true
  supervisor:
    enabled: true
    githubProviders:
      provider-name:
        clientId: <GITHUB_APP_CLIENT_ID>
        clientSecret: <GITHUB_APP_CLIENT_SECRET>
    federationDomains:
      domain-name:
        issuer: https://beam.your-domain.com/issuer-path
        tlsSecretName: <TLS_SECRET_NAME>
        identityProviders:
          provider-name:
            teams:
              - organization/your-dev-team
              - organization/your-devops-team
