{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sesamy.gtm-enrichment.name" . }}-namespace-only
  labels:
    {{- include "sesamy.gtm-enrichment.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm-enrichment.namespace" . }}
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector: {}
  egress:
    - to:
        - podSelector: {}
  ingress:
    - from:
        - podSelector: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sesamy.gtm-enrichment.name" . }}-egress-dns
  labels:
    {{- include "sesamy.gtm-enrichment.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm-enrichment.namespace" . }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "sesamy.gtm-enrichment.selectorLabels" . | nindent 6 }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sesamy.gtm-enrichment.name" . }}-ingress
  labels:
    {{- include "sesamy.gtm-enrichment.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm-enrichment.namespace" . }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - gtm-preview
          - gtm-tagging
    matchLabels:
      {{- include "sesamy.gtm-enrichment.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: http
          protocol: TCP
      {{- if .Values.networkPolicy.ingress.namespaceSelector }}
      from:
        - namespaceSelector:
          {{- toYaml .Values.networkPolicy.ingress.namespaceSelector | nindent 12 }}
          {{- if .Values.networkPolicy.ingress.podSelector }}
          podSelector:
          {{- toYaml .Values.networkPolicy.ingress.podSelector | nindent 12 }}
          {{- end }}
      {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sesamy.gtm-enrichment.name" . }}-ingress-metrics
  labels:
    {{- include "sesamy.gtm-enrichment.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm-enrichment.namespace" . }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      {{- include "sesamy.gtm-enrichment.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: http-metrics
          protocol: TCP
    {{- if .Values.networkPolicy.metrics.cidrs }}
      from:
      {{- range $cidr := .Values.networkPolicy.metrics.cidrs }}
        - ipBlock:
            cidr: {{ $cidr }}
      {{- end }}
      {{- if .Values.networkPolicy.metrics.namespaceSelector }}
        - namespaceSelector:
          {{- toYaml .Values.networkPolicy.metrics.namespaceSelector | nindent 12 }}
          {{- if .Values.networkPolicy.metrics.podSelector }}
          podSelector:
          {{- toYaml .Values.networkPolicy.metrics.podSelector | nindent 12 }}
          {{- end }}
      {{- end }}
    {{- end }}

{{- if .Values.networkPolicy.externalStorage.ports }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sesamy.gtm-enrichment.name" . }}-egress-external-storage
  labels:
    {{- include "sesamy.gtm-enrichment.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm-enrichment.namespace" . }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "sesamy.gtm-enrichment.selectorLabels" . | nindent 6 }}
  egress:
    - ports:
      {{- range $port := .Values.networkPolicy.externalStorage.ports }}
        - port: {{ $port }}
          protocol: TCP
      {{- end }}
  {{- if .Values.networkPolicy.externalStorage.cidrs }}
      to:
      {{- range $cidr := .Values.networkPolicy.externalStorage.cidrs }}
        - ipBlock:
            cidr: {{ $cidr }}
      {{- end }}
  {{- end }}
{{- end }}

{{- end }}

{{- if .Values.networkPolicy.discovery.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sesamy.gtm-enrichment.name" . }}-egress-discovery
  labels:
    {{- include "sesamy.gtm-enrichment.labels" . | nindent 4 }}
  namespace: {{ include "sesamy.gtm-enrichment.namespace" . }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "sesamy.gtm-enrichment.selectorLabels" . | nindent 6 }}
  egress:
    - ports:
        - port: {{ .Values.networkPolicy.discovery.port }}
          protocol: TCP
  {{- if .Values.networkPolicy.discovery.namespaceSelector }}
      to:
        - namespaceSelector:
          {{- toYaml .Values.networkPolicy.discovery.namespaceSelector | nindent 12 }}
          {{- if .Values.networkPolicy.discovery.podSelector }}
          podSelector:
          {{- toYaml .Values.networkPolicy.discovery.podSelector | nindent 12 }}
          {{- end }}
  {{- end }}
{{- end }}
