apiVersion: v2
name: sesamy-gtm
description: Helm chart for the Sesamy GTM tagging & preview service.
icon: https://avatars.githubusercontent.com/u/889755?s=200&v=4

type: application
version: 0.0.1
appVersion: 2.2.0
