apiVersion: v2
type: application
name: sesamy-gtm
description: Helm chart for the Sesamy GTM tagging & preview service.
icon: https://avatars.githubusercontent.com/u/889755?s=200&v=4
home: https://www.foomo.org
keywords:
  - foomo
  - sesamy
sources:
  - https://github.com/foomo/helm-charts
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/foomo/helm-charts
    - name: GTM Changelog
      url: https://developers.google.com/tag-platform/tag-manager/server-side/release-notes
dependencies:
  - name: loki
    alias: loki
    version: 6.6.1
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
version: 0.0.5
appVersion: 2.3.0
