{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "squadron.cronjob.fullname" . }}-data
  labels: {{- include "squadron.cronjob.labels" . | nindent 4 }}
  namespace: {{ include "squadron.cronjob.namespace" . }}
spec:
  accessModes: [{{ .Values.persistence.accessMode }}]
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
{{- end }}
