{{- if .Values.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nextjs.server.fullname" . }}
  labels: {{- include "nextjs.server.labels" . | nindent 4 }}
  namespace: {{ include "nextjs.server.namespace" . }}
spec:
  selector:
    matchLabels: {{- include "nextjs.server.selectorLabels" . | nindent 6 }}
  {{- with .Values.autoscaling.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.autoscaling.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
