apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextjs.server.fullname" . }}
  labels:
    {{- include "nextjs.server.labels" . | nindent 4 }}
    {{- with .Values.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "nextjs.server.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "nextjs.server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: prometheus
      port: 9200
      targetPort: 9200
    {{- range $key, $value := .Values.ports }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $key }}
    {{- end }}
