{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "keel.cronjob.fullname" . }}-data
  labels: {{- include "keel.cronjob.labels" . | nindent 4 }}
  namespace: {{ include "keel.cronjob.namespace" . }}
spec:
  accessModes: [{{ .Values.persistence.accessMode }}]
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
{{- end }}
{{- range $key, $value := .Values.cronjob.additionalVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key }}
  labels: {{- include "keel.cronjob.labels" $ | nindent 4 }}
  namespace: {{ include "keel.cronjob.namespace" $ }}
spec:
  {{- if $value.name }}
  volumeName: {{ $value.name }}
  {{- end }}
  accessModes: [ {{ default $value.accessMode "ReadWriteOnce" }} ]
  {{- with $value.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with $value.size }}
  resources:
    requests:
      storage: {{ . }}
  {{- end }}
---
{{- end }}
