# yaml-language-server: $schema=values.schema.json

# @schema
# type: string
# @schema
# -- Overrides the chart's name
# @section -- Overrides
nameOverride: ''
# @schema
# type: string
# @schema
# -- Overrides the chart's computed fullname
# @section -- Overrides
fullnameOverride: ''
# @schema
# type: string
# @schema
# -- The name of the Namespace to deploy
# @section -- Overrides
namespaceOverride: ''

# @schema
# type: object
# additionalProperties: true
# @schema
# -- Custom templates to inject
# @section -- General
templates: {}

# @schema
# type: object
# additionalProperties: true
# @schema
# -- Custom values to inject into templates
# @section -- General
templatesValues: {}
