{{- if .Values.cloudflared.enabled }}
# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beam.cloudflared.fullname" . }}
  labels:
    {{- include "beam.cloudflared.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflared.account | quote }},
      "TunnelID": {{ .Values.cloudflared.tunnelId | quote }},
      "TunnelSecret": {{ .Values.cloudflared.secret | quote }}
    }
{{- end }}
