# yaml-language-server: $schema=./../values.schema.json
clusterSecretStores:
  my-cluster-secret-store:
    annotations: {}
    labels: {}
    controller: ""
    conditions:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: my-namespace
      - namespaces:
          - my-namespace
    provider:
      aws:
        service: SecretsManager
        region: eu-central-1
        auth:
          jwt:
            serviceAccountRef:
              name: my-service-account
              namespace: my-namespace
