# yaml-language-server: $schema=./../values.schema.json
externalSecrets:
  my-secret:
    annotations: {}
    labels: {}
    refreshInterval: 1h
    refreshPolicy: Periodic
    secretStoreRef:
      name: my-cluster-secret-store
      kind: ClusterSecretStore
    target:
      name: my-k8s-secret   # defaults to the key name (my-secret)
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: Opaque
        metadata:
          annotations: {}
          labels: {}
        data:
          my-key: "{{ .my-key | b64dec }}"
    data:
      - secretKey: my-key
        remoteRef:
          key: /path/to/secret
          property: my-property
    dataFrom:
      - extract:
          key: /path/to/secret
