# yaml-language-server: $schema=./../values.schema.json
secrets:
  my-secret:
    annotations:
      replicator.v1.mittwald.de/replicate-to: ".*"
    data: {}

tlsSecrets:
  my-domain.com:
    annotations:
      replicator.v1.mittwald.de/replicate-to: ".*"
    data:
      tls.crt: ''
      tls.key: ''

dockerSecrets:
  hub.docker.com:
    annotations:
      replicator.v1.mittwald.de/replicate-to: ".*"
    data: '{...}'
