name: PR check

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6

      - name: Install helm-schema
        run: go install github.com/dadav/helm-schema/cmd/helm-schema@latest

      - uses: azure/setup-helm@v4

      - name: Run Helm plugin install
        run: |
          helm plugin install https://github.com/KnechtionsCoding/helm-schema-gen.git

      - name: Run Helm lint
        run: |
          make lint

      - name: Run Helm docs
        run: |
          make docs
          if ! git diff --exit-code; then
              echo "Documentation not up to date. Please run `make docs` and commit changes!" >&2
              exit 1
          fi

      - name: Run Helm schema
        run: |
          make schema
          if ! git diff --exit-code; then
              echo "Documentation not up to date. Please run `make schema` and commit changes!" >&2
              exit 1
          fi
