{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keel.server.fullname" . }}-env
  labels: {{- include "keel.server.labels" . | nindent 4 }}
  namespace: {{ include "keel.server.namespace" . }}
type: Opaque
stringData: {{ toYaml .Values.secretEnv | nindent 2 }}
---
{{- end }}
